package rule

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/atop/project-memory-palace/internal/store"
	"gopkg.in/yaml.v3"
)

type AgentRule struct {
	ID           string "yaml:\"id\" json:\"id\""
	SourceMemory string "yaml:\"source_memory\" json:\"source_memory\""
	Title        string "yaml:\"title\" json:\"title\""
	Category     string "yaml:\"category\" json:\"category\""
	Body         string "yaml:\"body\" json:\"body\""
	CreatedAt    string "yaml:\"created_at\" json:\"created_at\""
}

type RulesDocument struct {
	Version        int         "yaml:\"version\" json:\"version\""
	SynthesizedAt  string      "yaml:\"synthesized_at\" json:\"synthesized_at\""
	Rules          []AgentRule "yaml:\"rules\" json:\"rules\""
}

// Synthesize scans all active convention and decision cards and regenerates
// agent-rules.yaml. The file is written atomically (temp + rename).
func Synthesize(projectRoot string) (*RulesDocument, error) {
	cards, err := store.DiscoverCards(projectRoot)
	if err != nil {
		return nil, fmt.Errorf("synthesize: discover: %w", err)
	}

	now := time.Now().Format(time.RFC3339)
	doc := &RulesDocument{
		Version:       1,
		SynthesizedAt: now,
		Rules:         make([]AgentRule, 0),
	}

	n := 0
	for _, card := range cards {
		// Only active convention and decision cards become rules.
		if card.Status != "active" {
			continue
		}
		if card.Type != "convention" && card.Type != "decision" {
			continue
		}

		n++
		rule := AgentRule{
			ID:           fmt.Sprintf("rule_%03d", n),
			SourceMemory: card.ID,
			Title:        card.Title,
			Category:     card.Type,
			Body:         card.Content,
			CreatedAt:    now,
		}
		doc.Rules = append(doc.Rules, rule)
	}

	// Serialize to YAML
	data, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("synthesize: marshal: %w", err)
	}

	targetPath := store.RulesPath(projectRoot)
	tmp, err := os.CreateTemp(store.RulesDir(projectRoot), ".tmp-rules-*")
	if err != nil {
		return nil, fmt.Errorf("synthesize: tempfile: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return nil, fmt.Errorf("synthesize: write temp: %w", err)
	}
	tmp.Close()

	if err := os.Rename(tmpPath, targetPath); err != nil {
		os.Remove(tmpPath)
		return nil, fmt.Errorf("synthesize: rename: %w", err)
	}

	// Also write a Markdown version agents can directly consume.
	// This file goes to .project-memory/rules/agent-rules.md and is designed
	// to be loaded by AI agents (Claude Code, Cursor, etc.) via CLAUDE.md
	// or project configuration.
	mdPath := store.RulesPath(projectRoot)
	mdPath = mdPath[:len(mdPath)-len(".yaml")] + ".md"
	var md strings.Builder

	// Header: what this file IS and how agents should USE it
	md.WriteString("# 🏰 Project Memory Rules — AI Agent Instructions\n\n")
	md.WriteString("> **Auto-generated by pmem** from active convention & decision memory cards.\n")
	md.WriteString(fmt.Sprintf("> **Synthesized**: %s | **%d active rules** (stale/superseded/rejected cards excluded)\n\n", now, len(doc.Rules)))

	md.WriteString("## ⚠️  How to Use These Rules\n\n")
	md.WriteString("**You are an AI coding agent.** These rules were extracted from the project's\n")
	md.WriteString("memory cards and represent **verified, active conventions and decisions**.\n\n")
	md.WriteString("### Mandatory behaviors:\n\n")
	md.WriteString("1. **Follow conventions as law.** Convention rules describe mandatory code standards,\n")
	md.WriteString("   patterns, and practices. Violate them only with explicit user approval.\n")
	md.WriteString("2. **Respect decisions as constraints.** Decision rules record architectural choices\n")
	md.WriteString("   that have been made. Do not propose alternatives unless the decision is\n")
	md.WriteString("   explicitly marked stale or superseded.\n")
	md.WriteString("3. **Check freshness before trusting.** Each rule has a source memory ID. If you\n")
	md.WriteString("   suspect a rule is outdated, use `open_memory <id>` to inspect the full card\n")
	md.WriteString("   for its status and confidence.\n")
	md.WriteString("4. **Apply rules proactively.** When generating code, reviewing PRs, or answering\n")
	md.WriteString("   questions about this project, scan these rules FIRST and apply them.\n\n")

	md.WriteString("### Integration tips:\n\n")
	md.WriteString("- Load this file via `CLAUDE.md` or project configuration on session start.\n")
	md.WriteString("- Call the `synthesize_rules` MCP tool to get the latest rules programmatically.\n")
	md.WriteString("- Rules are NOT auto-regenerated. Call the `synthesize_rules` MCP tool to refresh them manually.\n\n")

	md.WriteString("---\n\n")

	if len(doc.Rules) == 0 {
		md.WriteString("_No active rules yet. Use `pmem remember` to create convention/decision cards._\n")
	} else {
		for _, rule := range doc.Rules {
			var icon string
			if rule.Category == "convention" {
				icon = "📐"
			} else {
				icon = "⚡"
			}
			md.WriteString(fmt.Sprintf("## %s %s\n\n", icon, rule.Title))
			md.WriteString(fmt.Sprintf("- **Category**: `%s`\n", rule.Category))
			md.WriteString(fmt.Sprintf("- **Source**: `%s` (use `open_memory %s` for full details)\n", rule.SourceMemory, rule.SourceMemory))
			md.WriteString(fmt.Sprintf("- **Rule ID**: `%s`\n\n", rule.ID))
			md.WriteString(rule.Body)
			md.WriteString("\n\n---\n\n")
		}
	}

	md.WriteString("## 📋 Rule Generation Info\n\n")
	md.WriteString(fmt.Sprintf("- **Source**: `.project-memory/cards/` → filtered by `status=active` + `type∈{convention,decision}`\n"))
	md.WriteString(fmt.Sprintf("- **Generated**: %s\n", now))
	md.WriteString("- **Next update**: manually via `pmem synthesize-rules` or the `synthesize_rules` MCP tool\n")

	tmp2, err := os.CreateTemp(store.RulesDir(projectRoot), ".tmp-rules-md-*")
	if err == nil {
		tmp2Path := tmp2.Name()
		tmp2.Write([]byte(md.String()))
		tmp2.Close()
		os.Rename(tmp2Path, mdPath)
	}

	return doc, nil
}
